// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR96Igm_azKq9Qhj9sx23xPkACcnKh0j0',
    appId: '1:99461162129:web:a74a738c15e86c6d3a0b30',
    messagingSenderId: '99461162129',
    projectId: 'lab0-tested-mocked',
    authDomain: 'lab0-tested-mocked.firebaseapp.com',
    storageBucket: 'lab0-tested-mocked.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDdhmqUilzsqLwUcfXdGXw3aK6yYryqrs',
    appId: '1:99461162129:android:ade2c98f60ed13c43a0b30',
    messagingSenderId: '99461162129',
    projectId: 'lab0-tested-mocked',
    storageBucket: 'lab0-tested-mocked.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDNP37DA2Ho9eNyWbYJye5FVuxZIclmvI',
    appId: '1:99461162129:ios:c0c2c2f787a8325c3a0b30',
    messagingSenderId: '99461162129',
    projectId: 'lab0-tested-mocked',
    storageBucket: 'lab0-tested-mocked.appspot.com',
    iosClientId: '99461162129-r1u1ktprl4sp54od5vo7lilpkb9hc38b.apps.googleusercontent.com',
    iosBundleId: 'com.fgunscot.fmbase',
  );
}
